### ISSUE TITLE
`Shopgoodwill` class isn't aware of the `CalculateShipping` api endpoint

### ISSUE THREAD

**Issue by RagingRoosevelt** [scottmconway/shopgoodwill-scripts#15]
`https://buyerapi.shopgoodwill.com/api/ItemDetail/CalculateShipping` can estimate the shipping cost for a given item to a given zip code.  This is useful for calculating the total current price of a listing, especially because it is often a significant cost factor for a listing at $10+.

**Comment by scottmconway** [comment]
Resolved in #17
