### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by RagingRoosevelt** [scottmconway/shopgoodwill-scripts#16]
Depending on what package is used to install the Crypto module, it may get installed as `crypto`.  Some `Crypto` modules such as `pycrypto` are defunct.  Suggest specifying `pycryptodome` in `requirements.txt` which is actively maintained and addresses the case issue for installed `Crypto` module.

**Comment by scottmconway** [comment]
Resolved in #17
