### ISSUE TITLE
Passing the Search Term to alert_on_new_query_results.py 

### ISSUE THREAD

**Issue by ngisvold** [scottmconway/shopgoodwill-scripts#21]
I could not get this to work for the life of me: alert_on_new_query_results.py -q shoes

Not clear to me in the documentation.

I was able to get saved query to run though! Awesome! Thanks so much!

**Comment by scottmconway** [comment]
The intent with local queries is to store an "advanced query" JSON (mentioned [here](https://github.com/scottmconway/shopgoodwill-scripts#query-generation)) in the config file, and then reference it by name when running `alert_on_new_query_results.py`. The example config has a saved query named `tuscon_pick_up_only`, shown [here](https://github.com/scottmconway/shopgoodwill-scripts/blob/main/config.json.example#L37). So if you were using the example config, you'd be able to run `alert_on_new_query_results.py -q tuscon_pick_up_only`.

Please let me know if there are any specific points that could be made clearer in the readme.

**Comment by ngisvold** [comment]
Sorry, I was confused. I was trying to pass the actual search term through the command line.
