### ISSUE TITLE
basic logging to stdout or file

### ISSUE THREAD

**Issue by derzahla** [scottmconway/shopgoodwill-scripts#23]
Thanks for your work on this, much appreciated.  Everything seems to work great from my testing.  So I set up a daemon to run for my wife(main reason for me looking into shopgoodwill automation) and the scheduled bid never went through.  No output from the script either to aid troubleshooting.  I don't have a gotify server, any way I can just log to STDOUT or a file?  Im sure this is a really basic question but im not well versed in python.  I tried a few things which have not worked.   Thanks!

**Comment by scottmconway** [comment]
This gave me a nudge to check out what's possible with [logging.config](https://docs.python.org/3/library/logging.config.html). I'll push a change shortly to make _all_ logging settings (handlers, formatting, log level per each handler) configurable under the JSON config file.

But for now, you can add an additional handler as you wish. You probably want a simple [FileHandler](https://docs.python.org/3/library/logging.handlers.html#filehandler).

**Comment by scottmconway** [comment]
@derzahla check out the changes made to the example config, and supply a simple FileHandler instead of a GotifyHandler:

eg in the handlers section:
```
    "fileHandler": {
        "class": "logging.FileHandler",
        "filename": "example.log",
        },
```

Then be sure to add the handler to your loggers in that section.

**Comment by derzahla** [comment]
hey, Scott.  I had looked at the same documentation you linked to hoping I could get it working and push my updates but had trouble with the FileHandler so instead just basically did a  's/self.logger/logging/g', which worked for logging to the console but was ugly.  Your way is much better of course, thanks a lot
