### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by JohnnyOmm** [scottmconway/shopgoodwill-scripts#26]
Getting error "
ERROR:shopgoodwill_bid_sniper
2 minutes ago

HTTPError getting info for item ID '201901219 - 403 Client Error: Forbidden for url: https://buyerapi.shopgoodwill.com/api/itemDetail/GetItemDetailModelByItemId/201901219"

**Comment by scottmconway** [comment]
SGW has been decently unstable over the last week or so. I've not seen 403s, but I I'm going to say that it's a problem on their side. Please follow up if you consistently get 40Xs in bid_sniper with valid credentials, if these return statuses differ from what you get in a browser.
