### ISSUE TITLE
TypeError: place_bid() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by apoctapus** [scottmconway/shopgoodwill-scripts#3]
I've been having fun learning about running Gotify on my NAS and I'm getting a lot of use out of alert_on_new_query_results.py.  Super cool.  I haven't run into any problems with your approach, it's all running great and I appreciate you writing this!

Now I'm playing with bid_sniper.py and it seems to run fine, then eventually throws the exception in the title.  

### when does it happen?

Every time I run `python3 bid_sniper.py.`  It seems to maybe happen at random intervals, as if when processing some kind of inconsistent result from shopgoodwill.com, but I haven't tested that theory.

### how to reproduce?

I favorited item 143389827 and added my bid to the notes, like `{ "max_bid": 9.7 }`

Then I run `bid_sniper.py` and waited for [my auction](https://shopgoodwill.com/item/143389827) to come to an end. 

### What's the full stack trace/exception/error?

```
INFO:shopgoodwill_bid_sniper:time alert - Lot A Filter 49mm Lens Filters Hoya Tiffen Promaster ending at 2022-05-07T01:02:00+00:00
Traceback (most recent call last):
  File "./bid_sniper.py", line 309, in <module>
    main()
  File "./bid_sniper.py", line 301, in main
    schedule.run_pending()
  File "/Users/carl/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/Users/carl/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/Users/carl/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/Users/carl/Library/Python/3.8/lib/python/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
TypeError: place_bid() takes 2 positional arguments but 3 were given
```

### Is there any relevant config I should know about?

These are my config.json settings:
```
    "bid_sniper": {
        "refresh_seconds": 300,
        "bid_snipe_time_delta": "30 seconds",
        "favorites_max_cache_seconds": 600,
        "alert_time_deltas": [
            "30 minutes",
            "15 minutes",
            "1 minute"
                    ]
    }
```

Let me know if I can try anything from here to gather more context.

**Comment by scottmconway** [comment]
Fixed in https://github.com/scottmconway/shopgoodwill-scripts/commit/e6a5ce97c5d11bebdf1050318900480943680a22

It seems I wasn't sure how I wanted to manage using the dry-run option at the time.

Thanks for checking out my scripts, and enjoy!
